version: '3'

services:
  esms-postgres-compose:
    image: postgres
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esms-database
    ports:
      - '15432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  esms-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '16543:80'
    depends_on:
      - esms-postgres-compose

volumes:
  database-data: # named volumes can be managed easier using docker-compose

